### ISSUE TITLE
undefined variables starting with _ underscore

### ISSUE THREAD

**Issue by monojk** [SYSPROG-JLS/S370BALEmulator#2]
Hi,
I'm running on windows and get this crash. I suspect it being related to 324 undefined references detected by pylance under Visual Studio Code ` like "_R1" is not defined`
What can I do to remedy this?
```
Traceback (most recent call last):
  File "c:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2570, in <module>
    program_counter = mach_inst[_OC][1]()
  File "c:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 1520, in MVCL
    instrdata_list[first_op_addr+i] = instrdata_list[secnd_op_addr+i]
IndexError: list index out of range
```

**Comment by SYSPROG-JLS** [comment]
<<I suspect it being related to 324 undefined references detected by pylance under Visual Studio Code  like "_R1" is not defined>>
I just think those messages are the result of running the emulator under VS Code.

This is the real problem:
File "c:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 1520, in MVCL
    instrdata_list[first_op_addr+i] = instrdata_list[secnd_op_addr+i]
IndexError: list index out of range

The emulator is having a problem with the MVCL instruction.
Please make sure you are following proper syntax and bounds for the MVCL instruction in your program.

If you can't find any problems then please send me your S/370 assembler source code so I can try to recreate the problem here. Be sure to include any data file(s) that your program might need to read.

**Comment by monojk** [comment]
Hi, thanks for looking.
Yet, the code doesn't use MVCL. Below is the code. Please note that I had to change the start of comments to e.g. sl[15:32] in the S370BALAsm.py. Can the start column for comments be made a parameter to the python program?   
```
*        TITLE 'MANDELBROT INNER LOOP SUBROUTINE, RESULT IN PARAM LST'
*         COPY  YREGS
         PRINT NOGEN         
* R1     address of parameter list
* R12    address pointer in subroutine
* R13    address of caller's save area
* R14    return address
* R15    address of subroutine's entry point
MANDELB  CSECT
*
         STM   14,12,12(13)     Save registers
         BALR  R12,0            Establish base register 
         USING *,R12
*
         L     R1,CREAL         Load real part of c into R1 
         L     R2,CIMAG         Load Imag part of c into R2 
         LR    R3,R1            Init real part of z to real part of c 
         LR    R4,R2            Init Imag part of z to Imag part of c 
         L     R5,MAXITER       Load maximum iteration count into R5 
*
ITERLOOP DS    0H
         LR    R7,R3            R7 = zr
         MR    R6,R7            R7 = zr**2
         SRA   R7,12            shift right to norm the result            
*
         LR    R9,R4            R9 = zi
         MR    R8,R9            R9 = zi**2 
         SRA   R9,12            shift right to norm the result            
*
         LR    R10,R7           R10 = zr**2 
         AR    R10,R9           R10 = zr**2 + zi**2 
*
         C     R10,LIMIT        Compare zr**2 + zi**2 with limit 4 norm
         BNL   ESCAPE           Branch if zr**2 + zi**2 >= 4 norm
*
         LR    R11,R7           R11 = zr**2
         SR    R11,R9           R11 = zr**2 - zi**2
         AR    R11,R1           R11 = zr**2 - zi**2 + CREAL
*
         SR    R8,R8            Clear R8
         LR    R9,R3            R9 = zr,  R8_R9 = zr
         MR    R8,R4            R9 = zr * zi
         SRA   R9,12            shift right to norm the result
         SLA   R9,1             multiply by 2
         AR    R9,R2            zi = 2 * zr * zi + CIMAG
*         
         LR    R3,R11           R3 : zr = zr**2 - zi**2 + CREAL
*                               for next iteration
         LR    R4,R9            R4 : 2 * zr * zi + CIMAG                 
*                               for next iteration
*
         B     CRASH
         BCT   R5,ITERLOOP      Decr iter cntr and branch if not zero 
         L     R1,ANSADDR       pointer to answer
         MVI   0(R1),C'*'       store result in param list
         B     ENDLOOP
ESCAPE   DS    0H
         L     R1,ANSADDR       pointer to answer
         MVI   0(R1),C'.'       store result in param list
ENDLOOP  DS    0H
         ST    R5,ITERCNT       Store iteration count in ITERCNT 
*         B     CRASH
* Restore registers and return
         L     14,12(13)        Restore registers
         LM    R14,R12,12(R13)
         XR    R15,R15          Return code 0
         BR    R14              Return 
* 
         LTORG 
CRASH    DC    D'0'             force crash
CREAL    DC    X'00001400'
CIMAG    DC    X'FFFFDAAB'
ANSADDR  DC    F'0'             Address of Answer               
MAXITER  DC    F'11'
ZERO     DC    F'0'
LIMIT    DC    X'00004000'      4 * 2**SHIFT
ITERCNT  DC    F'0'
SHIFT    EQU   12
ANS      DC    C'?'
ANSADDR  DC    A(ANS)
*
R0       EQU   0
R1       EQU   1
R2       EQU   2
R3       EQU   3
R4       EQU   4
R5       EQU   5
R6       EQU   6
R7       EQU   7
R8       EQU   8
R9       EQU   9
R10      EQU   10
R11      EQU   11
R12      EQU   12
R13      EQU   13
R14      EQU   14
R15      EQU   15
         END   MANDELB
```

**Comment by SYSPROG-JLS** [comment]
Hi monojk,

I was able to replicate your issue.

Your problem was caused by not commenting out the STM at the beginning of your program and commenting out the "L     14,12(13)" & LM at the end of your program.

This is documented in the README for S370BALAsm.
See below:

#
# Do NOT save registers 14-12 at beginning
# or restore them at the end as you would normally do.
#

Once I commented out those 3 lines of code (STM + "L     14,12(13)"  +  LM) then re-assembled your source using S370BALAsm, the S370BALEmulator ran without abending. 

As far as your suggestion for a param for the starting col for comments in S370BALAsm, I will think about that.

Thanks for your interest in my work!

Jim S

**Comment by SYSPROG-JLS** [comment]
Sorry, didn't intend to flame you. 
Didn't know that github would bold and enlarge the font the way it did  :>)

LMK if you have any other suggestions or need any further help.

**Comment by monojk** [comment]
Thanks alot. I'm able now to debug my program.

**Comment by monojk** [comment]
On another assembly, I get running the emulator. There is an outer loop of 50 and an inner of 100 iterations, so it's hard for me to step through. I set a breakpoint at the end of a loop, but the crash happens after some go statements.
Is there a good startegy?  
``` 
Traceback (most recent call last):
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2570, in <module>
    program_counter = mach_inst[_OC][1]()
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2049, in STH
    Store_code(2)
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 389, in Store_code
    instrdata_list[dest + i] = op1[j:j+2]
IndexError: list assignment index out of range
```

**Comment by SYSPROG-JLS** [comment]
Appears to be a bug in emulator- would you be so kind as to share your source code so I can replicate the abend?Thanks!!Sent from my iPhoneOn Jul 13, 2024, at 11:23, monojk ***@***.***> wrote:﻿
On another assembly, I get running the emulator. There is an outer loop of 50 and an inner of 100 iterations, so it's hard for me to step through. I set a breakpoint at the end of a loop, but the crash happens after some go statements before the breakpoint.
Is there a good startegy?
Traceback (most recent call last):
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2570, in <module>
    program_counter = mach_inst[_OC][1]()
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2049, in STH
    Store_code(2)
  File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 389, in Store_code
    instrdata_list[dest + i] = op1[j:j+2]
IndexError: list assignment index out of range

**Comment by monojk** [comment]
will open an issue with the code in the emulator repos.
